name: OTP CI Build

on:
  push:
  pull_request:
    branches:
      - openmove
jobs:
  build:
    runs-on: ubuntu-latest

    env:
      MAVEN_OPTS: -Xmx2g
    steps:
      # Starting in v2.2 checkout action fetches all tags when fetch-depth=0, for auto-versioning.
      - uses: actions/checkout@v2.3.2
        with:
          fetch-depth: 0
      # Java setup step completes very fast, no need to run in a preconfigured docker container.
      - name: Set up JDK 8
        uses: actions/setup-java@v1
        with:
          java-version: 8
      # Retain the local Maven repository to speed up builds.
      - name: Setup Maven Cache
        uses: actions/cache@v2
        id: cache
        with:
          path: ~/.m2
          key: maven-local-repo
      # So that the branch name can be reference via $GITHUB_HEAD_REF_SLUG.
      - name: Inject slug/short variables
        uses: rlespinasse/github-slug-action@v3.x
      # Build and test deployment.
      - name: Build and Test
        run: mvn clean verify --batch-mode --show-version --update-snapshots -Dgpg.skip
